Repository UFPB-Squad-Team/alpargatas-insights, pull requests merged in 2025-08, with the labels that each got.

#10 [ETL] Add transform script
  etl/scripts/02_transform.py
Labels: enhancement

#11 [ETL] Improves the transform script and generate the .parquet file
  .gitignore
  Makefile
  docs/DATA_SETUP.md
  etl/poetry.lock
  etl/pyproject.toml
  etl/scripts/02_transform.py
Labels: documentation, enhancement

#13 feat: implements new docker builder check workflow
  .github/workflows/build-check.yml
  etl/Dockerfile
Labels: enhancement

#14 feat: implements new pytest config
  .github/workflows/run-tests.yml
  etl/poetry.lock
  etl/pyproject.toml
  etl/scripts/Transform_advanced_infra.py
  etl/scripts/Transform_basic_infra.py
  etl/scripts/__init__.py
  etl/scripts/extract.py
  etl/scripts/load.py
  etl/scripts/transform.py
  etl/tests/__init__.py
  etl/tests/test_transform.py
Labels: enhancement

#15 [Infra] New workflow for data validation from transform script
  .env.example
  .github/workflows/data-validation.yml
  .gitignore
  Makefile
  etl/Dockerfile
  etl/data/raw/escolas_paraiba_sample.parquet
  etl/poetry.lock
  etl/pyproject.toml
  etl/scripts/validate_processed_data.py
Labels: enhancement

#16 [Client] Improves the client side configs
  client/.eslintrc.cjs
  client/eslint.config.js
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/index.css
  client/tailwind.config.ts
  client/tsconfig.json
  client/vite.config.ts
Labels: infra, frontend

#18 [Client][Dashboard] Implements the responsive layout with fixes components and dinamic components
  client/postcss.config.js
  client/public/images.svg
  client/public/logo.svg
  client/public/logo_no_background.svg
  client/public/vite.svg
  client/src/App.tsx
  client/src/components/layout/Layout.tsx
  client/src/components/layout/Menu.tsx
  client/src/components/layout/Navbar.tsx
  client/src/components/layout/Sidebar.tsx
  client/src/features/dashboard/DashboardPage.tsx
  client/src/main.tsx
  client/tailwind.config.js
  client/tailwind.config.ts
Labels: enhancement, frontend

#19 [Client][Dashboard] add new common Modal component, settingsModal surface and Notif…
  client/src/components/common/Modal.tsx
  client/src/components/layout/Layout.tsx
  client/src/components/layout/Navbar.tsx
  client/src/components/layout/NotificationsDropdown.tsx
  client/src/components/layout/SettingsModal.tsx
  client/src/hooks/useClickOutside.ts
Labels: enhancement, frontend

#21 [Client][Dashboard] Implements the Dashboard Page Layout with KPIs already and Priority Attention Listing
  .github/PULL_REQUEST_TEMPLATE.md
  client/src/features/dashboard/DashboardPage.tsx
  client/src/features/dashboard/components/HighRiskSchoolsList.tsx
  client/src/features/dashboard/components/InteractiveMap.jsx
  client/src/features/dashboard/components/InteractiveMap.tsx
  client/src/features/dashboard/components/KpiCard.jsx
  client/src/features/dashboard/components/KpiCard.tsx
  client/src/features/dashboard/components/PartneerNeedsCard.tsx
  client/src/features/dashboard/components/SchoolListItem.tsx
  client/src/mocks/services/getDashboardKPIs.ts
  client/src/mocks/services/getHighRiskSchools.ts
  client/src/mocks/services/searchSchools.ts
  client/tailwind.config.js
Labels: enhancement, frontend

#22 [API] feature: Add SearchSchoolsByNameUseCase and new repository method
  server/src/application/UseCases/SchoolUseCases/SearchSchoolsUseCase/SearchSchoolsDTO.ts
  server/src/application/UseCases/SchoolUseCases/SearchSchoolsUseCase/SearchSchoolsUseCase.ts
  server/src/domain/repositories/schoolRepository.ts
  server/src/tests/unit/DashboardUseCases/getDashboardKPIs.spec.ts
  server/src/tests/unit/SchoolUseCases/getSchoolDetails.spec.ts
  server/src/tests/unit/SchoolUseCases/getSchoolsByDependenciaAdministrativa.spec.ts
  server/src/tests/unit/SchoolUseCases/listSchoolForMap.spec.ts
  server/src/tests/unit/SchoolUseCases/searchSchoolsName.spec.ts
Labels: enhancement, api

#23 [Client][Dashboard] feat: implement the new map chart
  client/src/changey-markercluster.d.ts
  client/src/components/common/Modal.tsx
  client/src/components/common/RiskIndicator.tsx
  client/src/components/common/RiskLegend.tsx
  client/src/components/common/SearchInput.tsx
  client/src/components/common/Spinner.tsx
  client/src/components/layout/Sidebar.tsx
  client/src/features/dashboard/DashboardPage.tsx
  client/src/features/dashboard/components/CustomPopup.tsx
  client/src/features/dashboard/components/HighRiskSchoolsList.tsx
  client/src/features/dashboard/components/InteractiveMap.tsx
  client/src/features/dashboard/components/MapChart.tsx
  client/src/features/dashboard/components/SchoolListItem.tsx
  client/src/index.css
  client/src/mocks/data/school.mock.ts
  client/src/mocks/services/getSchoolsForMap.ts
Labels: enhancement, frontend

#27 [API] feat: Add errorHandling and app file
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/infrastructure/http/middleware/errorHandling.ts
  server/src/server.ts
Labels: enhancement, api

#28 [Client][Dashboard] Implements new Charts and Improves the Dashboard
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/common/RiskIndicator.tsx
  client/src/components/common/RiskLegend.tsx
  client/src/components/layout/Navbar.tsx
  client/src/components/layout/NotificationsDropdown.tsx
  client/src/context/DashboardContext.tsx
  client/src/features/dashboard/DashboardPage.tsx
  client/src/features/dashboard/components/CustomPopup.tsx
  client/src/features/dashboard/components/PartneerNeedsCard.tsx
  client/src/features/dashboard/components/cards/HighRiskSchoolsList.tsx
  client/src/features/dashboard/components/cards/KpiCard.tsx
  client/src/features/dashboard/components/cards/SchoolListItem.tsx
  client/src/features/dashboard/components/charts/MapChart.tsx
  client/src/features/dashboard/components/charts/RiskDistributionChart.tsx
  client/src/features/dashboard/components/charts/TopDeficienciesChart.tsx
  client/src/features/dashboard/components/charts/TopMunicipalitiesChart.tsx
  client/src/features/dashboard/components/custom/CustomPopup.tsx
  client/src/mocks/data/school.mock.ts
  client/src/mocks/services/getRiskDistribution.ts
  client/src/mocks/services/getTopDeficiencies.ts
  client/src/mocks/services/getTopMunicipalitiesByRisk.ts
Labels: enhancement, frontend

#36 [Client ][Api] Implements the new frontend architecture
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/domain/entities/PaginatedResponse.ts
  client/src/domain/entities/SchoolProps.ts
  client/src/domain/types/index.ts
  client/src/main.tsx
  client/src/modules/Dashboard/DashboardPage.tsx
  client/src/modules/Dashboard/components/cards/HighRiskSchoolsList.tsx
  client/src/modules/Dashboard/components/cards/KpiCard.tsx
  client/src/modules/Dashboard/components/cards/SchoolListItem.tsx
  client/src/modules/Dashboard/components/charts/MapChart.tsx
  client/src/modules/Dashboard/components/charts/RiskDistributionChart.tsx
  client/src/modules/Dashboard/components/charts/TopDeficienciesChart.tsx
  client/src/modules/Dashboard/components/charts/TopMunicipalitiesChart.tsx
  client/src/modules/Dashboard/components/custom/CustomPopup.tsx
  client/src/shared/lib/axios.ts
  client/src/shared/mocks/data/kpis.mock.ts
  client/src/shared/mocks/data/school.mock.ts
  client/src/shared/mocks/services/getDashboardKPIs.ts
  client/src/shared/mocks/services/getHighRiskSchools.ts
  client/src/shared/mocks/services/getRiskDistribution.ts
  client/src/shared/mocks/services/getSchoolsForMap.ts
  client/src/shared/mocks/services/getTopDeficiencies.ts
  client/src/shared/mocks/services/getTopMunicipalitiesByRisk.ts
  client/src/shared/mocks/services/searchSchools.ts
  client/src/shared/services/Schools/logic/searchSchoolsUseCase.ts
  client/src/shared/services/Schools/repositories/mappers/schoolMapper.ts
  client/src/shared/services/Schools/repositories/schoolRepository.ts
  client/src/ui/components/common/Modal.tsx
  client/src/ui/components/common/RiskIndicator.tsx
  client/src/ui/components/common/RiskLegend.tsx
  client/src/ui/components/common/SearchInput.tsx
  client/src/ui/components/common/Spinner.tsx
  client/src/ui/components/layout/Layout.tsx
  client/src/ui/components/layout/Menu.tsx
  client/src/ui/components/layout/Navbar.tsx
  client/src/ui/components/layout/NotificationsDropdown.tsx
  client/src/ui/components/layout/SettingsModal.tsx
  client/src/ui/components/layout/Sidebar.tsx
  client/src/ui/context/DashboardContext.tsx
  client/src/ui/hooks/useClickOutside.ts
  client/src/ui/hooks/useDebounce.ts
  server/src/app.ts
Labels: enhancement, api, frontend

#35 [API] feat: Add a express in compatible version for express-async-errors
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/infrastructure/database/repository/moongoseSchoolRepository.ts
Labels: enhancement, api

#30 [ETL] feat: Creates the load function
  etl/scripts/load.py
Labels: enhancement, etl

#39 [API] feat: Add new Municipality controller and route
  server/src/app.ts
  server/src/infrastructure/database/repository/moongoseMunicipalityRepository.ts
  server/src/infrastructure/database/repository/moongoseSchoolRepository.ts
  server/src/infrastructure/http/controller/MunicipalityController/GetMunicipalityStatisticsController/GetMunicipalityStatisticsController.ts
  server/src/infrastructure/http/controller/MunicipalityController/GetMunicipalityWithIbgeCodeController/GetMunicipalityWithIbgeCodeController.ts
  server/src/infrastructure/http/controller/MunicipalityController/ListMunicipalitiesController/ListMunicipalitiesController.ts
  server/src/infrastructure/http/controller/MunicipalityController/index.ts
  server/src/infrastructure/http/routes/municipalityRoutes.ts
Labels: enhancement, api

#40 [ETL] Adiciona o script requerido por Alessio
  .gitignore
  docs/relatoriotecnico.md
  etl/poetry.lock
  etl/pyproject.toml
  etl/scripts/gerar_dataset_final.py
  etl/scripts/professor_pipeline.py
Labels: documentation, enhancement, etl

#42 [ETL] feat: implements the new improved architecture etl
  .github/workflows/data-validation.yml
  Makefile
  docker-compose.yml
  etl/Dockerfile
  etl/config/pipeline_config.yml
  etl/dags/escolas_etl_dag.py
  etl/poetry.lock
  etl/pyproject.toml
  etl/scripts/extract.py
  etl/scripts/gerar_dataset_final.py
  etl/scripts/load.py
  etl/scripts/professor_pipeline.py
  etl/scripts/transform.py
  etl/src/__init__.py
  etl/src/common/__init__.py
  etl/src/common/database.py
  etl/src/common/utils.py
  etl/src/jobs/__init__.py
  etl/src/jobs/enriquecimento_pipeline/__init__.py
  etl/src/jobs/enriquecimento_pipeline/extract.py
  etl/src/jobs/enriquecimento_pipeline/main.py
  etl/src/jobs/enriquecimento_pipeline/transform.py
  etl/src/jobs/escolas_pipeline/__init__.py
  etl/src/jobs/escolas_pipeline/extract.py
  etl/src/jobs/escolas_pipeline/load.py
  etl/src/jobs/escolas_pipeline/main.py
  etl/src/jobs/escolas_pipeline/transform.py
  etl/src/jobs/escolas_pipeline/validate.py
  etl/tests/test_transform.py
Labels: enhancement, etl

#44 [API] doc: Add documentation for municipality routes
  docs/contracts/contratoApiMunicipality.md
Labels: documentation, api
