Repository UFPB-Squad-Team/alpargatas-insights, pull requests merged in 2025-09, with the labels that each got.

#68 [API] feat: Add healtcheck for docker
  server/src/app.ts
  server/src/infrastructure/configs/healthCheckDatabaseConnection.ts
  server/src/infrastructure/http/controller/HealthCheckControllers/HealthCheckController/HealthCheckController.ts
  server/src/infrastructure/http/controller/HealthCheckControllers/index.ts
  server/src/infrastructure/http/routes/healthCheckRoutes.ts
Labels: enhancement, api

#67 [ETL] feat: Add inse pipeline
  etl/src/jobs/inse_pipeline/__init__.py
  etl/src/jobs/inse_pipeline/extract.py
  etl/src/jobs/inse_pipeline/main.py
  etl/src/jobs/inse_pipeline/transform.py
  server/src/infrastructure/http/controller/HealthCheckControllers/HealthCheckController/HealthCheckController.ts
Labels: enhancement, etl

#69 [ETL] feat: Creates a IBGE 2010 censo pipeline
  .env.example
  etl/config/pipeline_config.yml
  etl/src/jobs/censo_pipeline/__init__.py
  etl/src/jobs/censo_pipeline/extract.py
  etl/src/jobs/censo_pipeline/main.py
  etl/src/jobs/censo_pipeline/transform.py
  etl/src/jobs/escolas_pipeline/transform.py
Labels: enhancement, etl

#74 [API] feat: Add new route for create need
  server/src/app.ts
  server/src/application/UseCases/NeedUseCases/CreateNeedUseCase/CreateNeedInputDTO.ts
  server/src/application/UseCases/NeedUseCases/CreateNeedUseCase/CreateNeedOutputDTO.ts
  server/src/application/UseCases/NeedUseCases/CreateNeedUseCase/CreateNeedUseCase.ts
  server/src/domain/entities/need.ts
  server/src/domain/validators/needValidator.ts
  server/src/infrastructure/configs/models/moongoseNeedModel.ts
  server/src/infrastructure/database/repository/moongoseNeedRepository.ts
  server/src/infrastructure/http/controller/NeedController/CreateNeedController/CreateNeedController.ts
  server/src/infrastructure/http/controller/NeedController/index.ts
  server/src/infrastructure/http/routes/needRoutes.ts
  server/src/infrastructure/mapper/needMapper.ts
Labels: enhancement, api

#75 [API] feat: Add list need with approved
  server/src/application/UseCases/NeedUseCases/ListApprovedNeedUseCase/ListApprovedNeedInputDTO.ts
  server/src/application/UseCases/NeedUseCases/ListApprovedNeedUseCase/ListApprovedNeedOutputDTO.ts
  server/src/application/UseCases/NeedUseCases/ListApprovedNeedUseCase/ListApprovedNeedUseCase.ts
  server/src/infrastructure/configs/models/moongoseNeedModel.ts
  server/src/infrastructure/database/repository/moongoseNeedRepository.ts
  server/src/infrastructure/http/controller/NeedController/ListApprovedNeedController/ListApprovedNeedController.ts
  server/src/infrastructure/http/controller/NeedController/index.ts
  server/src/infrastructure/http/routes/needRoutes.ts
Labels: enhancement, api

#72 [ETL] feat: improves escolas_pipeline to handle with new enrich data from ml
  etl/config/pipeline_config.yml
  etl/src/jobs/enriquecimento_pipeline/__init__.py
  etl/src/jobs/enriquecimento_pipeline/extract.py
  etl/src/jobs/enriquecimento_pipeline/main.py
  etl/src/jobs/enriquecimento_pipeline/transform.py
  etl/src/jobs/escolas_pipeline/enrich.py
  etl/src/jobs/escolas_pipeline/load.py
  etl/src/jobs/escolas_pipeline/main.py
Labels: enhancement, etl

#71 [ML] feat: implements the new model training pipeline to diagnostic contex…
  .gitignore
  README.md
  docs/API-endpoint-map.md
  docs/data_governance.md
  docs/relatoriotecnico.md
  model-training-pipeline/config/config.yaml
  model-training-pipeline/src/jobs/ml_pipeline_v2/job_01_data_preparation_v2.py
  model-training-pipeline/src/jobs/ml_pipeline_v2/job_02_feature_engineering_v2.py
  model-training-pipeline/src/jobs/ml_pipeline_v2/job_03_train_evaluate_v2.py
  model-training-pipeline/src/jobs/ml_pipeline_v2/job_04_calculate_context_score_v2.py
  model-training-pipeline/src/jobs/ml_pipeline_v2/main.py
Labels: enhancement, machine learning

#79 [API] feat: Add new filters and kpis from Institute
  server/src/application/UseCases/DashboardUseCases/GetDashboardKPIsUseCase/GetDashboardKPIsDTO.ts
  server/src/application/UseCases/DashboardUseCases/GetDashboardKPIsUseCase/GetDashboardKPIsUseCase.ts
  server/src/application/UseCases/DashboardUseCases/RiskDistributionDashboardUseCase/RiskDistributionDashboardUseCase.ts
  server/src/domain/repositories/schoolRepository.ts
  server/src/infrastructure/database/repository/moongoseSchoolRepository.ts
  server/src/infrastructure/http/controller/MunicipalityController/GetAllMunicipalitiesWithHighRiskSchool/GetAllMunicipalitiesWithHighRiskSchool.ts
  server/src/tests/unit/DashboardUseCases/getDashboardKPIs.spec.ts
Labels: enhancement, api
